apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mjml
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: '0.0.37'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    schedule: '0 8 * * *'
    timeZone: 'Europe/Paris'
    nameOverride: mjml
    image:
      name: rg.fr-par.scw.cloud/vibioh/mjml
      tag: '202506022146' # {"$imagepolicy": "default:flux-mjml-api:tag"}
    labels:
      tags.datadoghq.com/env: 'production'
      tags.datadoghq.com/service: 'mjml'
      tags.datadoghq.com/version: '202506022146' # {"$imagepolicy": "default:flux-mjml-api:tag"}
    env:
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    config:
      MJML_LISTEN_DURATION: '180'
      MJML_LISTEN_PORT: '3000'
      OTEL_ENDPOINT_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/mjml-api
    port: 3000
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
