apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mjml
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.1.2'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: mjml
    podAnnotations:
    image:
      name: vibioh/mjml
      tag: '202412162313' # {"$imagepolicy": "default:flux-mjml-api:tag"}
    labels:
      tags.datadoghq.com/env: 'production'
      tags.datadoghq.com/service: 'mjml'
      tags.datadoghq.com/version: '202412162313' # {"$imagepolicy": "default:flux-mjml-api:tag"}
    env:
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    port: 3000
    config:
      OTEL_ENDPOINT_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/mjml-api
    probes:
      readiness: /health
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
    autoscaling:
      enabled: false
