apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mjml
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.80'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: mjml
    podAnnotations:
    image:
      name: vibioh/mjml
      tag: '202202201025' # {"$imagepolicy": "default:flux-mjml-api:tag"}
    port: 3000
    config:
      JAEGER_ENDPOINT: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: mjml-api
    prometheus:
      port: 3000
    probes:
      readiness: /health
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 96Mi
