---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjml
  labels:
    app.kubernetes.io/name: mjml
    app.kubernetes.io/instance: mjml
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    matchLabels:
      name: mjml
  template:
    metadata:
      labels:
        name: mjml
    spec:
      containers:
        - name: funds
          image: vibioh/mjml
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests:
              memory: 24M
            limits:
              memory: 64M
