---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mjml
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mjml
    app.kubernetes.io/version: latest
  name: mjml
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: mjml
    app.kubernetes.io/name: mjml
