#!/usr/bin/env bash

diffInitial=`git diff --name-only --diff-filter=ACMR`

BLUE='\033[0;34m'
RED='\033[0;31m'
RESET='\033[0m'

package=`git diff --cached --name-only --diff-filter=ACMR | grep -E "package.json$"`
js=`git diff --cached --name-only --diff-filter=ACMR | grep -E "js$"`

pass=0

npmInstall="false"

function checkInstall() {
  if [ "${npmInstall}" == "true" ]; then
      return
  fi

  echo -e "${BLUE}Installing NPM dependencies${RESET}"
  npmInstall="true"

  if command -v npm > /dev/null 2>&1; then
    npm --silent install --ignore-scripts --no-audit

    pass=$?
  else
    echo -e "${RED}npm not found in $PATH, check status of ${BLUE}package-lock.json{RESET}"
  fi
}

function build() {
  checkInstall

  if command -v npm > /dev/null 2>&1; then
    npm --silent run build

    pass=$?
  else
    echo -e "${RED}npm not found in $PATH, check status of ${BLUE}dist/{RESET}"
  fi
}

if [ "${package}" != "" ]; then
  checkInstall
fi

if [ "${pass}" == "0" ] && [ "${js}" != "" ]; then
  build
fi

if [ ! "${pass}" == "0" ]; then
    echo -e "${RED}COMMIT FAILED${RESET}"
    echo -e "${RED}Last check failed during pre-commit. Please fix errors and try committing again.${RESET}"

    exit 1
fi

diffFinal=`git diff --name-only --diff-filter=ACMR`

if [ ! "$diffInitial" == "$diffFinal" ]; then
  echo -e "${RED}Pre-commit has changes files${RESET}"
  echo -e "${RED}Consider adding updated files with ${BLUE}git add -i \&\& git commit --amend${RESET}"
fi

exit 0
